# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import cell_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='hypothesis.proto',
  package='ProtoMsg',
  serialized_pb='\n\x10hypothesis.proto\x12\x08ProtoMsg\x1a\ncell.proto\"E\n\x04Leak\x12&\n\x08location\x18\x01 \x02(\x0b\x32\x14.ProtoMsg.Coordinate\x12\x15\n\rconcentration\x18\x02 \x02(\x01\"g\n\nHypothesis\x12\x13\n\x0bprobability\x18\x01 \x02(\x01\x12\x1c\n\x04leak\x18\x02 \x03(\x0b\x32\x0e.ProtoMsg.Leak\x12&\n\rmethene_cells\x18\x03 \x03(\x0b\x32\x0f.ProtoMsg.Cells\"/\n\nHypotheses\x12!\n\x03hyp\x18\x01 \x03(\x0b\x32\x14.ProtoMsg.Hypothesis\"8\n\x12Hypotheses_history\x12\"\n\x04hyps\x18\x01 \x03(\x0b\x32\x14.ProtoMsg.Hypotheses')




_LEAK = descriptor.Descriptor(
  name='Leak',
  full_name='ProtoMsg.Leak',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='location', full_name='ProtoMsg.Leak.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='concentration', full_name='ProtoMsg.Leak.concentration', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=111,
)


_HYPOTHESIS = descriptor.Descriptor(
  name='Hypothesis',
  full_name='ProtoMsg.Hypothesis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='probability', full_name='ProtoMsg.Hypothesis.probability', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leak', full_name='ProtoMsg.Hypothesis.leak', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='methene_cells', full_name='ProtoMsg.Hypothesis.methene_cells', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=216,
)


_HYPOTHESES = descriptor.Descriptor(
  name='Hypotheses',
  full_name='ProtoMsg.Hypotheses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hyp', full_name='ProtoMsg.Hypotheses.hyp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=218,
  serialized_end=265,
)


_HYPOTHESES_HISTORY = descriptor.Descriptor(
  name='Hypotheses_history',
  full_name='ProtoMsg.Hypotheses_history',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hyps', full_name='ProtoMsg.Hypotheses_history.hyps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=267,
  serialized_end=323,
)

_LEAK.fields_by_name['location'].message_type = cell_pb2._COORDINATE
_HYPOTHESIS.fields_by_name['leak'].message_type = _LEAK
_HYPOTHESIS.fields_by_name['methene_cells'].message_type = cell_pb2._CELLS
_HYPOTHESES.fields_by_name['hyp'].message_type = _HYPOTHESIS
_HYPOTHESES_HISTORY.fields_by_name['hyps'].message_type = _HYPOTHESES
DESCRIPTOR.message_types_by_name['Leak'] = _LEAK
DESCRIPTOR.message_types_by_name['Hypothesis'] = _HYPOTHESIS
DESCRIPTOR.message_types_by_name['Hypotheses'] = _HYPOTHESES
DESCRIPTOR.message_types_by_name['Hypotheses_history'] = _HYPOTHESES_HISTORY

class Leak(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEAK
  
  # @@protoc_insertion_point(class_scope:ProtoMsg.Leak)

class Hypothesis(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPOTHESIS
  
  # @@protoc_insertion_point(class_scope:ProtoMsg.Hypothesis)

class Hypotheses(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPOTHESES
  
  # @@protoc_insertion_point(class_scope:ProtoMsg.Hypotheses)

class Hypotheses_history(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPOTHESES_HISTORY
  
  # @@protoc_insertion_point(class_scope:ProtoMsg.Hypotheses_history)

# @@protoc_insertion_point(module_scope)
