# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import hypothesis_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dect.proto',
  package='Msg',
  serialized_pb='\n\ndect.proto\x12\x03Msg\x1a\x10hypothesis.proto\"2\n\tDetection\x12\x0c\n\x04time\x18\x01 \x02(\x05\x12\x17\n\x04leak\x18\x02 \x03(\x0b\x32\t.Msg.Leak\"*\n\nDetections\x12\x1c\n\x04\x64\x65\x63t\x18\x01 \x03(\x0b\x32\x0e.Msg.Detection')




_DETECTION = descriptor.Descriptor(
  name='Detection',
  full_name='Msg.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='Msg.Detection.time', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leak', full_name='Msg.Detection.leak', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=87,
)


_DETECTIONS = descriptor.Descriptor(
  name='Detections',
  full_name='Msg.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dect', full_name='Msg.Detections.dect', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=131,
)

_DETECTION.fields_by_name['leak'].message_type = hypothesis_pb2._LEAK
_DETECTIONS.fields_by_name['dect'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS

class Detection(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETECTION
  
  # @@protoc_insertion_point(class_scope:Msg.Detection)

class Detections(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETECTIONS
  
  # @@protoc_insertion_point(class_scope:Msg.Detections)

# @@protoc_insertion_point(module_scope)
