# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cell.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cell.proto',
  package='Message',
  serialized_pb='\n\ncell.proto\x12\x07Message\"?\n\nCoordinate\x12\x0f\n\x07\x63oord_x\x18\x01 \x02(\x05\x12\x0f\n\x07\x63oord_y\x18\x02 \x02(\x05\x12\x0f\n\x07\x63oord_z\x18\x03 \x02(\x05\"\xc6\x02\n\x04\x43\x65ll\x12\"\n\x05\x63oord\x18\x01 \x02(\x0b\x32\x13.Message.Coordinate\x12\x1d\n\x03tag\x18\x02 \x02(\x0e\x32\x10.Message.CellTag\x12\"\n\x03mtn\x18\x03 \x02(\x0b\x32\x15.Message.Cell.Methane\x12 \n\x04wind\x18\x04 \x02(\x0b\x32\x12.Message.Cell.Wind\x1a\x36\n\nWindVector\x12\x0c\n\x04wv_x\x18\x01 \x02(\x01\x12\x0c\n\x04wv_y\x18\x02 \x02(\x01\x12\x0c\n\x04wv_z\x18\x03 \x02(\x01\x1a[\n\x04Wind\x12&\n\x04wind\x18\x01 \x02(\x0b\x32\x18.Message.Cell.WindVector\x12+\n\tpotential\x18\x02 \x02(\x0b\x32\x18.Message.Cell.WindVector\x1a \n\x07Methane\x12\x15\n\rconcentration\x18\x01 \x02(\x01\"$\n\x05\x43\x65lls\x12\x1b\n\x04\x63\x65ll\x18\x01 \x03(\x0b\x32\r.Message.Cell\"r\n\x03Map\x12\'\n\nstartIndex\x18\x01 \x02(\x0b\x32\x13.Message.Coordinate\x12%\n\x08\x62oundary\x18\x02 \x02(\x0b\x32\x13.Message.Coordinate\x12\x1b\n\x04\x63\x65ll\x18\x03 \x03(\x0b\x32\r.Message.Cell*,\n\x07\x43\x65llTag\x12\x07\n\x03\x41ir\x10\x01\x12\n\n\x06Ground\x10\x02\x12\x0c\n\x08\x42uilding\x10\x03')

_CELLTAG = _descriptor.EnumDescriptor(
  name='CellTag',
  full_name='Message.CellTag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Air', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ground', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Building', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=571,
  serialized_end=615,
)

CellTag = enum_type_wrapper.EnumTypeWrapper(_CELLTAG)
Air = 1
Ground = 2
Building = 3



_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='Message.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coord_x', full_name='Message.Coordinate.coord_x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coord_y', full_name='Message.Coordinate.coord_y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coord_z', full_name='Message.Coordinate.coord_z', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=86,
)


_CELL_WINDVECTOR = _descriptor.Descriptor(
  name='WindVector',
  full_name='Message.Cell.WindVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wv_x', full_name='Message.Cell.WindVector.wv_x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wv_y', full_name='Message.Cell.WindVector.wv_y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wv_z', full_name='Message.Cell.WindVector.wv_z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=234,
  serialized_end=288,
)

_CELL_WIND = _descriptor.Descriptor(
  name='Wind',
  full_name='Message.Cell.Wind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wind', full_name='Message.Cell.Wind.wind', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='potential', full_name='Message.Cell.Wind.potential', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=381,
)

_CELL_METHANE = _descriptor.Descriptor(
  name='Methane',
  full_name='Message.Cell.Methane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='concentration', full_name='Message.Cell.Methane.concentration', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=383,
  serialized_end=415,
)

_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='Message.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coord', full_name='Message.Cell.coord', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='Message.Cell.tag', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtn', full_name='Message.Cell.mtn', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind', full_name='Message.Cell.wind', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CELL_WINDVECTOR, _CELL_WIND, _CELL_METHANE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=415,
)


_CELLS = _descriptor.Descriptor(
  name='Cells',
  full_name='Message.Cells',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell', full_name='Message.Cells.cell', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=417,
  serialized_end=453,
)


_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='Message.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startIndex', full_name='Message.Map.startIndex', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boundary', full_name='Message.Map.boundary', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell', full_name='Message.Map.cell', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=455,
  serialized_end=569,
)

_CELL_WINDVECTOR.containing_type = _CELL;
_CELL_WIND.fields_by_name['wind'].message_type = _CELL_WINDVECTOR
_CELL_WIND.fields_by_name['potential'].message_type = _CELL_WINDVECTOR
_CELL_WIND.containing_type = _CELL;
_CELL_METHANE.containing_type = _CELL;
_CELL.fields_by_name['coord'].message_type = _COORDINATE
_CELL.fields_by_name['tag'].enum_type = _CELLTAG
_CELL.fields_by_name['mtn'].message_type = _CELL_METHANE
_CELL.fields_by_name['wind'].message_type = _CELL_WIND
_CELLS.fields_by_name['cell'].message_type = _CELL
_MAP.fields_by_name['startIndex'].message_type = _COORDINATE
_MAP.fields_by_name['boundary'].message_type = _COORDINATE
_MAP.fields_by_name['cell'].message_type = _CELL
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['Cells'] = _CELLS
DESCRIPTOR.message_types_by_name['Map'] = _MAP

class Coordinate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COORDINATE

  # @@protoc_insertion_point(class_scope:Message.Coordinate)

class Cell(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class WindVector(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CELL_WINDVECTOR

    # @@protoc_insertion_point(class_scope:Message.Cell.WindVector)

  class Wind(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CELL_WIND

    # @@protoc_insertion_point(class_scope:Message.Cell.Wind)

  class Methane(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CELL_METHANE

    # @@protoc_insertion_point(class_scope:Message.Cell.Methane)
  DESCRIPTOR = _CELL

  # @@protoc_insertion_point(class_scope:Message.Cell)

class Cells(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CELLS

  # @@protoc_insertion_point(class_scope:Message.Cells)

class Map(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAP

  # @@protoc_insertion_point(class_scope:Message.Map)


# @@protoc_insertion_point(module_scope)
