// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dect.proto

#ifndef PROTOBUF_dect_2eproto__INCLUDED
#define PROTOBUF_dect_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "hypothesis.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtoMsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dect_2eproto();
void protobuf_AssignDesc_dect_2eproto();
void protobuf_ShutdownFile_dect_2eproto();

class Detection;
class Detections;

// ===================================================================

class Detection : public ::google::protobuf::Message {
 public:
  Detection();
  virtual ~Detection();
  
  Detection(const Detection& from);
  
  inline Detection& operator=(const Detection& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Detection& default_instance();
  
  void Swap(Detection* other);
  
  // implements Message ----------------------------------------------
  
  Detection* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Detection& from);
  void MergeFrom(const Detection& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);
  
  // repeated .ProtoMsg.Leak leak = 2;
  inline int leak_size() const;
  inline void clear_leak();
  static const int kLeakFieldNumber = 2;
  inline const ::ProtoMsg::Leak& leak(int index) const;
  inline ::ProtoMsg::Leak* mutable_leak(int index);
  inline ::ProtoMsg::Leak* add_leak();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Leak >&
      leak() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Leak >*
      mutable_leak();
  
  // @@protoc_insertion_point(class_scope:ProtoMsg.Detection)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Leak > leak_;
  ::google::protobuf::int32 time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_dect_2eproto();
  friend void protobuf_AssignDesc_dect_2eproto();
  friend void protobuf_ShutdownFile_dect_2eproto();
  
  void InitAsDefaultInstance();
  static Detection* default_instance_;
};
// -------------------------------------------------------------------

class Detections : public ::google::protobuf::Message {
 public:
  Detections();
  virtual ~Detections();
  
  Detections(const Detections& from);
  
  inline Detections& operator=(const Detections& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Detections& default_instance();
  
  void Swap(Detections* other);
  
  // implements Message ----------------------------------------------
  
  Detections* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Detections& from);
  void MergeFrom(const Detections& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ProtoMsg.Detection dect = 1;
  inline int dect_size() const;
  inline void clear_dect();
  static const int kDectFieldNumber = 1;
  inline const ::ProtoMsg::Detection& dect(int index) const;
  inline ::ProtoMsg::Detection* mutable_dect(int index);
  inline ::ProtoMsg::Detection* add_dect();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Detection >&
      dect() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Detection >*
      mutable_dect();
  
  // @@protoc_insertion_point(class_scope:ProtoMsg.Detections)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Detection > dect_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dect_2eproto();
  friend void protobuf_AssignDesc_dect_2eproto();
  friend void protobuf_ShutdownFile_dect_2eproto();
  
  void InitAsDefaultInstance();
  static Detections* default_instance_;
};
// ===================================================================


// ===================================================================

// Detection

// required int32 time = 1;
inline bool Detection::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Detection::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Detection::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Detection::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 Detection::time() const {
  return time_;
}
inline void Detection::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// repeated .ProtoMsg.Leak leak = 2;
inline int Detection::leak_size() const {
  return leak_.size();
}
inline void Detection::clear_leak() {
  leak_.Clear();
}
inline const ::ProtoMsg::Leak& Detection::leak(int index) const {
  return leak_.Get(index);
}
inline ::ProtoMsg::Leak* Detection::mutable_leak(int index) {
  return leak_.Mutable(index);
}
inline ::ProtoMsg::Leak* Detection::add_leak() {
  return leak_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Leak >&
Detection::leak() const {
  return leak_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Leak >*
Detection::mutable_leak() {
  return &leak_;
}

// -------------------------------------------------------------------

// Detections

// repeated .ProtoMsg.Detection dect = 1;
inline int Detections::dect_size() const {
  return dect_.size();
}
inline void Detections::clear_dect() {
  dect_.Clear();
}
inline const ::ProtoMsg::Detection& Detections::dect(int index) const {
  return dect_.Get(index);
}
inline ::ProtoMsg::Detection* Detections::mutable_dect(int index) {
  return dect_.Mutable(index);
}
inline ::ProtoMsg::Detection* Detections::add_dect() {
  return dect_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Detection >&
Detections::dect() const {
  return dect_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoMsg::Detection >*
Detections::mutable_dect() {
  return &dect_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoMsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dect_2eproto__INCLUDED
